#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Получаем предыдущую версию из main
PREV_VERSION=$(git show origin/main:package.json | jq -r .version)
# Получаем новую версию
NEW_VERSION=$(jq -r .version package.json)

if [ "$PREV_VERSION" = "$NEW_VERSION" ]; then
  echo "❌ Ошибка: Перед пушем в main обнови версию в package.json!"
  exit 1
fi

echo "✅ Версия обновлена. Пуш разрешён."
